package proxies.ext.fedps_giac;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T16:54:02.891+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://fedps.giac.transport/", name = "delivery")
@XmlSeeAlso({ObjectFactory.class})
public interface Delivery {

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "order", targetNamespace = "http://fedps.giac.transport/", className = "proxies.ext.fedps_giac.Order")
    @WebMethod
    @ResponseWrapper(localName = "orderResponse", targetNamespace = "http://fedps.giac.transport/", className = "proxies.ext.fedps_giac.OrderResponse")
    public proxies.ext.fedps_giac.ResponseOrder order(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.fedps_giac.OrderRequest message
    ) throws DeliveryFault_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "estimation", targetNamespace = "http://fedps.giac.transport/", className = "proxies.ext.fedps_giac.Estimation")
    @WebMethod
    @ResponseWrapper(localName = "estimationResponse", targetNamespace = "http://fedps.giac.transport/", className = "proxies.ext.fedps_giac.EstimationResponse")
    public proxies.ext.fedps_giac.ResponseEstimation estimation(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.fedps_giac.EstimationRequest message
    ) throws DeliveryFault_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "track", targetNamespace = "http://fedps.giac.transport/", className = "proxies.ext.fedps_giac.Track")
    @WebMethod
    @ResponseWrapper(localName = "trackResponse", targetNamespace = "http://fedps.giac.transport/", className = "proxies.ext.fedps_giac.TrackResponse")
    public proxies.ext.fedps_giac.ResponseTrack track(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.fedps_giac.TrackRequest message
    ) throws DeliveryFault_Exception;
}
