
package proxies.ext.fedps_giac;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T18:29:30.936+01:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "DeliveryFault", targetNamespace = "http://fedps.giac.transport.external/")
public class DeliveryFault_Exception extends Exception {
    
	private static final long serialVersionUID = -6631189479907631362L;
	
	private proxies.ext.fedps_giac.DeliveryFault deliveryFault;

    public DeliveryFault_Exception() {
        super();
    }
    
    public DeliveryFault_Exception(String message) {
        super(message);
    }
    
    public DeliveryFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DeliveryFault_Exception(String message, proxies.ext.fedps_giac.DeliveryFault deliveryFault) {
        super(message);
        this.deliveryFault = deliveryFault;
    }

    public DeliveryFault_Exception(String message, proxies.ext.fedps_giac.DeliveryFault deliveryFault, Throwable cause) {
        super(message, cause);
        this.deliveryFault = deliveryFault;
    }

    public proxies.ext.fedps_giac.DeliveryFault getFaultInfo() {
        return this.deliveryFault;
    }
}
