package proxies.ext.warehouse_david;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-24T20:03:47.297+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "WareHouse", 
                  wsdlLocation = "file:./src/main/resources/warehouse_david.wsdl",
                  targetNamespace = "http://service.warehouse.external/") 
public class WareHouse extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.warehouse.external/", "WareHouse");
    public final static QName WareHouseServicePort = new QName("http://service.warehouse.external/", "WareHouseServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:./src/main/resources/warehouse_david.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WareHouse.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:./src/main/resources/warehouse_david.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WareHouse(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WareHouse(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WareHouse() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WareHouseService
     */
    @WebEndpoint(name = "WareHouseServicePort")
    public WareHouseService getWareHouseServicePort() {
        return super.getPort(WareHouseServicePort, WareHouseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WareHouseService
     */
    @WebEndpoint(name = "WareHouseServicePort")
    public WareHouseService getWareHouseServicePort(WebServiceFeature... features) {
        return super.getPort(WareHouseServicePort, WareHouseService.class, features);
    }

}
