package proxies.ext.crm_xinyi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T17:11:21.297+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "Crm", 
                  wsdlLocation = "file:/C:/Users/user/git/bug-marmelade/mistergooddeal/src/main/resources/crm_xinyi.wsdl",
                  targetNamespace = "http://xinyi.crm.external/") 
public class Crm extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xinyi.crm.external/", "Crm");
    public final static QName CrmServicePort = new QName("http://xinyi.crm.external/", "CrmServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/user/git/bug-marmelade/mistergooddeal/src/main/resources/crm_xinyi.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Crm.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/user/git/bug-marmelade/mistergooddeal/src/main/resources/crm_xinyi.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Crm(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Crm(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Crm() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CrmService
     */
    @WebEndpoint(name = "CrmServicePort")
    public CrmService getCrmServicePort() {
        return super.getPort(CrmServicePort, CrmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrmService
     */
    @WebEndpoint(name = "CrmServicePort")
    public CrmService getCrmServicePort(WebServiceFeature... features) {
        return super.getPort(CrmServicePort, CrmService.class, features);
    }

}
