
package proxies.ext.crm_xinyi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T17:11:21.261+01:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "CrmExceptions", targetNamespace = "http://xinyi.crm.external/")
public class CrmExceptions_Exception extends Exception {
    
	private static final long serialVersionUID = -1363829800126773685L;
	
	private proxies.ext.crm_xinyi.CrmExceptions crmExceptions;

    public CrmExceptions_Exception() {
        super();
    }
    
    public CrmExceptions_Exception(String message) {
        super(message);
    }
    
    public CrmExceptions_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CrmExceptions_Exception(String message, proxies.ext.crm_xinyi.CrmExceptions crmExceptions) {
        super(message);
        this.crmExceptions = crmExceptions;
    }

    public CrmExceptions_Exception(String message, proxies.ext.crm_xinyi.CrmExceptions crmExceptions, Throwable cause) {
        super(message, cause);
        this.crmExceptions = crmExceptions;
    }

    public proxies.ext.crm_xinyi.CrmExceptions getFaultInfo() {
        return this.crmExceptions;
    }
}
