package proxies.ext.crm_xinyi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T17:11:21.277+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://xinyi.crm.external/", name = "CrmService")
@XmlSeeAlso({ObjectFactory.class})
public interface CrmService {

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.AddOrder")
    @WebMethod
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.AddOrderResponse")
    public proxies.ext.crm_xinyi.ResponseAddOrder addOrder(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.AddOrderRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.GetCustomer")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.GetCustomerResponse")
    public proxies.ext.crm_xinyi.ResponseGetCustomer getCustomer(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.DeleteCustomerRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "deleteOrder", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.DeleteOrder")
    @WebMethod
    @ResponseWrapper(localName = "deleteOrderResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.DeleteOrderResponse")
    public proxies.ext.crm_xinyi.ResponseDeleteCustomer deleteOrder(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.DeleteOrderRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "searchCatalog", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.SearchCatalog")
    @WebMethod
    @ResponseWrapper(localName = "searchCatalogResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.SearchCatalogResponse")
    public proxies.ext.crm_xinyi.ResponseSearchCatalog searchCatalog(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.SearchCatalogRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.CreateCustomer")
    @WebMethod
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.CreateCustomerResponse")
    public proxies.ext.crm_xinyi.ResponseCreateCustomer createCustomer(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.CreateCustomerRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "deleteCustomer", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.DeleteCustomer")
    @WebMethod
    @ResponseWrapper(localName = "deleteCustomerResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.DeleteCustomerResponse")
    public proxies.ext.crm_xinyi.ResponseDeleteCustomer deleteCustomer(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.DeleteCustomerRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerOrder", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.GetCustomerOrder")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerOrderResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.GetCustomerOrderResponse")
    public proxies.ext.crm_xinyi.ResponseGetCustomerOrder getCustomerOrder(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.DeleteCustomerRequest message
    ) throws CrmExceptions_Exception;

    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerPreferredProducts", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.GetCustomerPreferredProducts")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerPreferredProductsResponse", targetNamespace = "http://xinyi.crm.external/", className = "proxies.ext.crm_xinyi.GetCustomerPreferredProductsResponse")
    public proxies.ext.crm_xinyi.ResponseGetCustomerPreferredProducts getCustomerPreferredProducts(
        @WebParam(name = "message", targetNamespace = "")
        proxies.ext.crm_xinyi.DeleteCustomerRequest message
    ) throws CrmExceptions_Exception;
}
