
package proxies.ext.crm_xinyi;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T17:11:21.077+01:00
 * Generated source version: 2.5.1
 * 
 */
public final class CrmService_CrmServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://xinyi.crm.external/", "Crm");

    private CrmService_CrmServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Crm.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Crm ss = new Crm(wsdlURL, SERVICE_NAME);
        CrmService port = ss.getCrmServicePort();  
        
        {
        System.out.println("Invoking addOrder...");
        proxies.ext.crm_xinyi.AddOrderRequest _addOrder_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseAddOrder _addOrder__return = port.addOrder(_addOrder_message);
            System.out.println("addOrder.result=" + _addOrder__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomer...");
        proxies.ext.crm_xinyi.DeleteCustomerRequest _getCustomer_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseGetCustomer _getCustomer__return = port.getCustomer(_getCustomer_message);
            System.out.println("getCustomer.result=" + _getCustomer__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteOrder...");
        proxies.ext.crm_xinyi.DeleteOrderRequest _deleteOrder_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseDeleteCustomer _deleteOrder__return = port.deleteOrder(_deleteOrder_message);
            System.out.println("deleteOrder.result=" + _deleteOrder__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking searchCatalog...");
        proxies.ext.crm_xinyi.SearchCatalogRequest _searchCatalog_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseSearchCatalog _searchCatalog__return = port.searchCatalog(_searchCatalog_message);
            System.out.println("searchCatalog.result=" + _searchCatalog__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createCustomer...");
        proxies.ext.crm_xinyi.CreateCustomerRequest _createCustomer_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseCreateCustomer _createCustomer__return = port.createCustomer(_createCustomer_message);
            System.out.println("createCustomer.result=" + _createCustomer__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteCustomer...");
        proxies.ext.crm_xinyi.DeleteCustomerRequest _deleteCustomer_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseDeleteCustomer _deleteCustomer__return = port.deleteCustomer(_deleteCustomer_message);
            System.out.println("deleteCustomer.result=" + _deleteCustomer__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomerOrder...");
        proxies.ext.crm_xinyi.DeleteCustomerRequest _getCustomerOrder_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseGetCustomerOrder _getCustomerOrder__return = port.getCustomerOrder(_getCustomerOrder_message);
            System.out.println("getCustomerOrder.result=" + _getCustomerOrder__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomerPreferredProducts...");
        proxies.ext.crm_xinyi.DeleteCustomerRequest _getCustomerPreferredProducts_message = null;
        try {
            proxies.ext.crm_xinyi.ResponseGetCustomerPreferredProducts _getCustomerPreferredProducts__return = port.getCustomerPreferredProducts(_getCustomerPreferredProducts_message);
            System.out.println("getCustomerPreferredProducts.result=" + _getCustomerPreferredProducts__return);

        } catch (CrmExceptions_Exception e) { 
            System.out.println("Expected exception: CrmExceptions has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
